### ISSUE TITLE
Study NLO QCD sampes and request for 2017

### ISSUE THREAD

**Issue by ahinzmann** [Diboson3D/cmgtools-lite#44]
In addition to Pythia/Herwig/Madgraph, we have a flat NLO QCD samples for the first time available: Dijet_NNPDF30_powheg_pythia8_TuneCUETP8M1_13TeV_bornktmin150
I thinks it is worth running on it quickly for 2016, to check that the statistics with the weights (since it’s kind of flat but in a strange way) is good for VV hadronic and then request this sample also for the 2017 analysis.

**Comment by thaarres** [comment]
Studied in 2016. Is this enough or request 2017 sample?
