### ISSUE TITLE
Signal fits

### ISSUE THREAD

**Issue by jngadiub** [Diboson3D/cmgtools-lite#8]
* improve the parametrization of the fit parameters for both mJ and mJJ (see attached example)
![jj_xqw_mjj_json_mean](https://user-images.githubusercontent.com/5583089/29924181-67a7fbf8-8e5c-11e7-9158-7778c4ba622a.png)
* include in the main code a script that plots all the extrapolated shapes to debug the parametrization (include also the extrapolated signal yields)

**Comment by clelange** [comment]
You mean something like that? This is drawn directly from the JSON file.

![signalshapes_lnuj_xww](https://user-images.githubusercontent.com/5270053/29977904-5a970808-8f3f-11e7-8bd6-bcb32743b709.png)

**Comment by jngadiub** [comment]
Exactly!Can you share the script?I can include this check in the main code.

**Comment by clelange** [comment]
Cherry-pick this commit: https://github.com/clelange/cmgtools-lite/commit/7ef1f4af0891f9eae2d3495fae561b23a0cdad53 (I'll see if you just copy and paste, it's great test of your git skills 😆 )
